# vim: ft=sh

. ~/.tq84-dotfile-sequence .bash_profile

if  [[ -r ~/.profile ]]; then
        echo $(date) .bash_profile: ~/.profile exists, sourcing it >> ~/.dotfile-sequence.log
        . ~/.profile
fi

case "$-" in *i*)
   echo $(date) - .bash_profile: \$- indicates an interactive shell  >> ~/.dotfile-sequence.log
   if [ -r ~/.bashrc ]; then
         echo $(date) - .bash_profile: ~/.bashrc exists, sourcing it >> ~/.dotfile-sequence.log
         . ~/.bashrc;
   fi;;
esac
