# vi: ft=sh
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# -----------------------------------------------

# https://wiki.archlinux.org/index.php/openbox
# https://wiki.archlinux.org/index.php/Xinit

# _{ Starting programs 
#
#    'man xinit': An important point is that programs which are
#    run by .xinitrc should be run in the background if they do
#    not exit right away, so that they don't prevent other programs
#    from starting up.
#    However, the last long lived program started (usually a window
#    manager or terminal emulator) shuld be left in the foreground
#    so that script won't exit (which indicates that the user is
#    done and that xinit should exit)
#

if [ $(hostname) == LFS_1 ]; then #_{

  twm                           &
  xclock -geometry 50x50-1+1    &
  xterm  -geometry 80x50+494+51 &
  xterm  -geometry 80x20+494-0  &

  exec xterm -geometry 80x66+0+0 -name login

fi #_}


xscreensaver                        &
xsetroot      -cursor_name left_ptr &

# volumeicon
# ----------
#
# pacman -S volumeicon
#
# 2017-07-11: Uncommenting:
#   Whenever volumeicon is used to mute
#   the sound, it cannot be unmuted again
#   with volumeicon. Instead, I had to
#   unmute it with
#     sudo amixer sset Master unmute
#    (http://renenyffenegger.ch/notes/Linux/sound/index)
#
# volumeicon                        &


#
#  Starting the »long lived« program.
#  This is usually a window manager or a terminal emulator.
#
#  Note: specifying »exec openbox« instead of
#       »exec openbox-session« will prevent autostart
#        in /etc/xdg/autostart
#
exec openbox-session

#_}
